freeze Werkzeug version at 2.3.7 * this is the latest version that aconf can be run with * fixes Flask 2.1.1 runtime error: `ImportError: cannot import name 'url_quote' from 'werkzeug.urls`
Flask and Werkzeug need to be kept in sync over major versions